---
# handlers file for wordpress
- name: "Restart mysql service"
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: "Restart apache service"
  ansible.builtin.service:
    name: apache2
    state: restarted
